- name: Get the latest version from GitHub repository
  ansible.builtin.uri:
    url: "https://api.github.com/repos/sigp/lighthouse/releases/latest"
    method: GET
    status_code: 200
    return_content: true
  register: _latest_release_response

- name: Set the version variable
  ansible.builtin.set_fact:
    _lighthouse_version: "{{ _latest_release_response.json.tag_name }}"

- name: Validate the discovered lighthouse version
  ansible.builtin.assert:
    that: _lighthouse_version is search("^v[0-9]+\.[0-9]+\.[0-9]+$")
    fail_msg: "Discovered version [{{ _lighthouse_version }}] is not valid"

- name: Information
  debug:
    msg: "Latest lighthouse version is {{ _lighthouse_version }}"