---
- name: Ensure we have sane configuration
  block:
    - fail:
        msg: You must set "lighthouse_version" for this role to run
      when: lighthouse_version is not defined

# Retrive latest version when lighthouse_version == 'latest'
- name: Include task to retrieve latest version
  ansible.builtin.include_tasks: "latest.yml"
  when: lighthouse_version == 'latest'

- name: Get IP address to bind to if not provided
  ansible.builtin.include_tasks: "network.yml"
  when: not lighthouse_host_ip

- name: Install lighthouse
  ansible.builtin.include_tasks: "install.yml"

- name: Start beacon
  ansible.builtin.include_tasks: "beacon.yml"
  when: lighthouse_beacon_enabled

- name: Start validator
  ansible.builtin.include_tasks: "validator.yml"
  when: lighthouse_validator_enabled

- name: Set version info on a local file
  ansible.builtin.include_tasks: "tags.yml"
