---
- name: Ensure we have sane configuration
  block:
    - fail:
        msg: You must set "lighthouse_version" for this role to run
      when: lighthouse_version is not defined

- name: Get IP address to bind to if not provided
  include_tasks: "network.yml"
  when: not lighthouse_host_ip

- name: Install lighthouse
  include_tasks: "install.yml"

- name: Start beacon
  include_tasks: "beacon.yml"
  when: lighthouse_beacon_enabled

- name: Start validator
  include_tasks: "validator.yml"
  when: lighthouse_validator_enabled
